#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🔍 Checking staged files..."
npx lint-staged

if [ $? -eq 0 ]; then
  echo "✅ Pre-commit checks passed!"
else
  echo "❌ Pre-commit checks failed!"
  exit 1
fi